# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12grpc_service.proto\x12\x0cgrpc_service\"\n\n\x08list_req\")\n\x08list_res\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\r\n\x05\x66iles\x18\x02 \x03(\t\"\x1f\n\nsearch_req\x12\x11\n\tfile_name\x18\x01 \x01(\t\"P\n\nsearch_res\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x14\n\x0c\x66ile_to_find\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x0c\n\x04path\x18\x04 \x01(\t2\x88\x01\n\x0c\x66ileServices\x12\x38\n\x04list\x12\x16.grpc_service.list_req\x1a\x16.grpc_service.list_res\"\x00\x12>\n\x06search\x12\x18.grpc_service.search_req\x1a\x18.grpc_service.search_res\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LIST_REQ._serialized_start=36
  _LIST_REQ._serialized_end=46
  _LIST_RES._serialized_start=48
  _LIST_RES._serialized_end=89
  _SEARCH_REQ._serialized_start=91
  _SEARCH_REQ._serialized_end=122
  _SEARCH_RES._serialized_start=124
  _SEARCH_RES._serialized_end=204
  _FILESERVICES._serialized_start=207
  _FILESERVICES._serialized_end=343
# @@protoc_insertion_point(module_scope)
